### ISSUE TITLE
Fix Map Coloring

### ISSUE THREAD

**Issue by sam-mata** [sam-mata/covid-visualiser#32]
Several areas of map colouring should be improved.

## Todo:
- [ ] @nathanbridgeearney Correct mis-matches between original dataset and new formatting, including USA, Ireland, Czechia, Lithuania, Estonia, Serbia, North Macedonia, Greece, Turkmenistan, India, Bangladesh, Malaysia, Ivory Coast, Guinea-Bissau, Democratic Republic of the Congo, Republic of the Congo, Tanzania, and Eswatini
- [x] @sam-mata Implement better colour-scaling for each feature _(e.g. min-max scaling)_

**Comment by nathanbridgeearney** [comment]
Are your changes on a particular branch @sam-mata?
